import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { MapIcon, User } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-sm border-b border-gray-200">
          <div className="max-w-7xl mx-auto px-4 py-4">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-xl font-bold text-gray-900">ThaiTravel</h1>
                <p className="text-sm text-gray-500">ค้นพบที่เที่ยวในฝัน</p>
              </div>
              <div>
                <Link href="/map">
                  <MapIcon className="w-6 h-6 text-gray-600" />
                  แผนที่
                </Link>
              </div>
              <div className="flex items-center gap-3">
                <button className="p-2 rounded-lg hover:bg-gray-100">
                  <User className="w-6 h-6 text-gray-600" />
                </button>
              </div>
            </div>
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
